name:  CommandButtons
description: Lets you set commands that buttons can perform when used.
version: 1.0
author: Freaxy
main: io.github.freaxy.CommandButtons
database: false
commands:
   cb:
      description: Use to set, clear or view the command for the button you're looking at.
      usage: /<command> [set/clear/show]
      aliases:  [CommandButtons, CommandButton]

permissions:
    CommandButtons.*:
        description: Gives access to all commands.
        children:
           CommandButtons.set: true
           CommandButtons.view: true
    CommandButtons.edit:
        description: Allows you to set commands for buttons.
        default: op
    CommandButtons.view:
        description: Allows you to see commands set for buttons.
        default: op